APIMessageBottle/config/routes.rb
APIMessageBottle::Application.routes.draw do
  resources :messages
  resources :users

  #API
  match "/newMess/:uid/:texte" => "api#newMess"
end

APIMessageBottle/app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :texte, :user_id

  belongs_to :user

end

APIMessageBottle/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :uid, :msg_send

  has_many :messages

  def incrementNbrMess
    self.msg_send += 1
    save!
  end
end

APIMessageBottle/app/controllers/api_controller.rb
class ApiController < ApplicationController
  include ActionView::Helpers::TextHelper

  respond_to :json, :js

  before_filter :initialisation

  def initialisation
    @reponse = Hash.new
  end

  #Formate la reponse en json et l'envoi
  def reponse msg
    @reponse["msg"] = msg
    respond_with(@reponse) do |format|
      format.js  { render :json => @reponse, :callback => params[:callback] }
    end
  end

  def newMess
    user = User.find_by_uid(params[:uid])
    unless user.nil?
      Message.create!(user_id: Random.new.rand(0..User.count), texte: truncate(params[:texte], length: 140, omission: ''))
      user.incrementNbrMess
      reponse "OK"
    else
      reponse "KO"
    end
  end
end

APIMessageBottle/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

APIMessageBottle/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  respond_to :html, :json

  def index
    @messages = Message.all
    respond_with @messages
  end

  def show
    @message = Message.find(params[:id])
    respond_with @messages
  end

  def new
    @message = Message.new
  end

  def edit
    @message = Message.find(params[:id])
  end

  def create
    @message = Message.create!(user_id: Random.new.rand(1..User.count), texte: params[:message][:texte])
    respond_with @messages
  end

  def update
    @message = Message.find(params[:id])
    @message.update_attributes(params[:message])
    respond_with @messages
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    respond_with @messages
  end
end

APIMessageBottle/app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :html, :json

  def index
    @users = User.all
    respond_with @users
  end

  def show
    @user = User.find(params[:id])
    respond_with @users
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    @user.save
    respond_with @users
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    respond_with @users
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with @users
  end
end

APIMessageBottle/app/helpers/api_helper.rb
module ApiHelper
end

APIMessageBottle/app/helpers/application_helper.rb
module ApplicationHelper
end

APIMessageBottle/app/helpers/messages_helper.rb
module MessagesHelper
end

APIMessageBottle/app/helpers/users_helper.rb
module UsersHelper
end

APIMessageBottle/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>APIMessageBottle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

APIMessageBottle/app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :texte %><br />
    <%= f.text_area :texte %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

APIMessageBottle/app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

APIMessageBottle/app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>User</th>
    <th>Texte</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.user_id %></td>
    <td><%= message.texte %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

APIMessageBottle/app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

APIMessageBottle/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @message.user_id %>
</p>

<p>
  <b>Texte:</b>
  <%= @message.texte %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

APIMessageBottle/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

APIMessageBottle/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

APIMessageBottle/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Uid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.uid %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

APIMessageBottle/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

APIMessageBottle/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uid:</b>
  <%= @user.uid %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>